--- #YAML:1.0
name: Class-DBI-SAK
version: 1.3
license: perl
distribution_type: module
requires:
  Class::DBI: 0
recommends:
  Class::DBI::AbstractSearch: 0
  Class::DBI::Join: 0
  Class::DBI::Pager: 0
build_requires:
  Class::DBI::AbstractSearch: 0
  Class::DBI::Join: 0
  Class::DBI::Pager: 0
  Module::Build: 0
  Test::More: 0
  mixin: 0
conflicts: {}
generated_by: Module::Build version 0.16
