--- #YAML:1.0
build_requires:
  Class::DBI::AbstractSearch: 0
  Class::DBI::Join: 0
  Class::DBI::Pager: 0
  Test::More: 0
  mixin: 0
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.13
license: perl
name: Class-DBI-SAK
recommends: {}
requires:
  Class::DBI: 0
version: 1.2
